name : s2-cloudcover-terratorch

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pyyaml
  - wget
  - tqdm
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - ipykernel
  - gdal
  - tensorboard
  - xarray-spatial